### ISSUE TITLE
Resource SiteBuilderFunction does not exist for stack AWSPics

### ISSUE THREAD

**Issue by iokobi** [jpsim/AWSPics#14]
Hi JP,

Getting the error below when running the deploy script.

`An error occurred (ValidationError) when calling the DescribeStackResource operation: Resource SiteBuilderFunction does not exist for stack AWSPics`

What am I doing wrong?

**Comment by iokobi** [comment]
Figured out the issue. :)

**Comment by jpsim** [comment]
Mind sharing what the problem was and how you solved it? I'm sure it could be helpful to others.

**Comment by iokobi** [comment]
> Mind sharing what the problem was and how you solved it? I'm sure it could be helpful to others.

I took a closer look at the CloudFormation Events and saw that the S3 buckets I specified in the config.json file already existed. 

`**Status Reason:** <s3-bucket-name> already exists`

I deleted the S3 buckets and the deploy script worked as expected.

**Comment by jpsim** [comment]
👍 thanks for sharing!

**Comment by ranarauf68** [comment]
This didn't work for me. I deleted the bucket, but am still getting same error.
