### ISSUE TITLE
Stack name issue

### ISSUE THREAD

**Issue by andsso** [jpsim/AWSPics#15]
Hey all

have the following issue with the deploy script:

Uploading to 82f57676ab14fe89375a0ec2398442f3  2359567 / 2359567.0  (100.00%)
Successfully packaged artifacts and wrote output template to file /tmp/tmp.ltdw0                               kTUmq.
Execute the following command to deploy the packaged template
aws cloudformation deploy --template-file /tmp/tmp.ltdw0kTUmq --stack-name YOUR                                STACK NAME

Expecting value: line 14 column 1 (char 3213)

An error occurred (ValidationError) when calling the DescribeStackResource opera                               tion: Stack 'AWSPics' does not exist
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: outfile

Anyone had this?

**Comment by muige** [comment]
I had the same issue. For me it was a syntax error in your config.json.  

Check that all lines (except the last one) has a comma in the end. If you copy-pasted the example config from the Readme, remove all comments from the config.json file.
