### ISSUE TITLE
AWSPics Costs

### ISSUE THREAD

**Issue by taylorbrooks** [jpsim/AWSPics#18]
Just curious, what are the estimated ongoing costs for AWSPics? I know, in large part, it's due to how many items are stored in your source bucket. Moving that aside, is there anything else that is ongoing?

**Comment by jpsim** [comment]
My personal set up is extremely cheap. $1-$2 / month. Hard to say exactly without some significant analysis since I have a bunch of other stuff in AWS that's included in my billing. That's with a few thousand pictures, ~20 albums and ~80 people with access.

**Comment by jpsim** [comment]
hell yeah!
