### ISSUE TITLE
Can the S3 buckets be encrypted server-side ?

### ISSUE THREAD

**Issue by gapo** [jpsim/AWSPics#20]
First - thanks for making this. This is amazing.
My question is about the S3 bucket storage encryption.
If I enable the Amazon S3 default encryption or say the SSE-KMS encryption for all the three buckets, do you think this would still continue working ?
Any potential issues you see with that ? 

Thanks !

**Comment by jpsim** [comment]
That’s a good question. I don’t know if that would work, but I’m curious to learn if you figure it out!

**Comment by gapo** [comment]
Thank you. We can close this for now. I will update if and when I find the answer.
