### ISSUE TITLE
Node version of Lambdas needs to be upgraded to 8.10

### ISSUE THREAD

**Issue by tgrecojr** [jpsim/AWSPics#23]
Amazon is deprecating Node 6.10, which is used by 2 of the lambda functions.

"Lambda functions configured to use the node.js 6.10 runtime will be disabled on April 30, 2019. Code updates to existing functions using node.js 6.10 will be disabled 30 days later on May 30, 2019."

**Comment by jpsim** [comment]
Updated in #22.
