### ISSUE TITLE
bcrypt module not compatible with nodejs12.x

### ISSUE THREAD

**Issue by liwani** [jpsim/AWSPics#28]
AWS discontinued support for nodejs8.10. I changed the code to nodejs12.x based on previous commit that updated project nodejs version. This caused an error with bcrypt module:
```json
"errorMessage": "The module '/var/task/node_modules/bcrypt/lib/binding/bcrypt_lib.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 57. This version of Node.js requires\nNODE_MODULE_VERSION 72. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`)."
```
I tried to replace bcrypt in lambda-login.zip with the latest version but it didn't help. Unfortunately, I don't know enough about nodejs deployment to quickly resolve it. I was wondering if you are planning to update to latest supported nodejs version?

**Comment by jpsim** [comment]
No I'm not planning on making changes to this project in the near future.

**Comment by agstevens** [comment]
From the AWS discontinuation notice.
> For Node.js 8.x, there will be 2 stages to the runtime deprecation process:
> 
> Disable Function Create – Beginning January 6, 2020, customers will no longer be able to create functions using Node.js 8.10
> 
> Disable Function Update – Beginning February 3, 2020, customers will no longer be able to update functions using Node.js 8.10

So no one can deploy this until we fix it.
I just started playing around with getting this working with nodejs10.x.

Login and resize seem to work fine changing from nodejs8.10 to nodejs10.x
site-builder has some issues. It is compiling, but the lambda function is not being generated when I deploy.

One change I made locally so far in the package.json in site-builder, I upgraded mime:
"dependencies": {
    "async": "^2.1.4",
    "mime": "^2.0.5",
    "js-yaml": "^3.8.4"
  }
...and I renamed the lookup() function to getType() in the two places it appears.
https://www.npmjs.com/package/mime (Mime 2.0+ breaks the current code)

Site-builder is still having an issue deploying. Any suggestions for where to look to fix it?

Thanks jpsim for making this, it's useful.

**Comment by agstevens** [comment]
Actually I seemed to have fixed it -Site-Builder was built later in the cloudformation process, after the cloudfront deployment. I'll submit a change shortly that should make it deployable.

**Comment by liwani** [comment]
Thanks Andrew. I cloned your branch and finally was able to successfully
deploy the project in AWS!

**Comment by agstevens** [comment]
I fixed the bcrypt EOL in https://github.com/jpsim/AWSPics/pull/49
Now it uses bcrypt 5.0.1+ instead of bcrypt 2.0.1 which had reached End of Life.

**Comment by agstevens** [comment]
Marking closed with latest PR https://github.com/jpsim/AWSPics/pull/49
