### ISSUE TITLE
lambda-login.zip missing in deploy execution

### ISSUE THREAD

**Issue by rwilsonvt** [jpsim/AWSPics#31]
Step 8/8 : CMD ["cat", "/build/dist.zip"]
 ---> Using cache
 ---> 385619951be4
Successfully built 385619951be4
Successfully tagged cloudformation-lambda-login:latest
./deploy: line 20: ../dist/lambda-login.zip: No such file or directory

Am i supposed to zip the folders?

**Comment by rwilsonvt** [comment]
Assume this is related to docker build on my server.

**Comment by LeeDayley-Wellsky** [comment]
What was your solution to this?  I am getting the exact same error.
