### ISSUE TITLE
Choice to make this public or private

### ISSUE THREAD

**Issue by jsloan117** [jpsim/AWSPics#34]
I still enjoy this project! My use for this is for my astrophotography site which I've modified this to make it public. I just wanted to engage everyone else evolved in this project on whether or not this would be liked by others and merged if I did the work while providing an option to select public site vs the default of private.

**Comment by jpsim** [comment]
Yeah it makes sense to me to want to disable the authentication part of this. The thought had never even crossed my mind that it would be useful for that.

**Comment by jsloan117** [comment]
Cool I'll give it some thought on how to execute this plan and will update as progress is made.

**Comment by brettswift** [comment]
👍 
One thought if it doesn't complicate the implication too much,  would be to 'whitelist' specific albums. 

You could probably do this at the cloudfront & DNS level,  via `album1.awspics.net` as a link to a specific album and whitelist that entry in the cloudfront rules.

**Comment by tylerapplebaum** [comment]
@jsloan117 I would love to see an option to disable authentication. I plan to deploy your fork shortly.

**Comment by jsloan117** [comment]
Thanks for the feedback on this. I haven't had much time to work on this sadly. I don't think my current fork works honestly haven't checked in a long time and not since these bigger changes were made. I don't plan on keeping my fork manager which is why I'm trying to get the public side to merge into the base code so I don't have to try and maintain it separately.

I have worked on this today, and more or less what I've come up with so far with the least amount of work is to duplicate the app.yml and maybe the deploy script. This code would simply remove the login/API stuff to remove the password protection. What I have so far doesn't work, but will continue to work on it in my free time.

**Comment by tylerapplebaum** [comment]
I ended up deploying a mix of your branch @jsloan117 and the parent project, since I needed nodejs 10.x. 

It is working, which is fantastic.

**Comment by jsloan117** [comment]
I'd be interested in what/how you did that. Again its been a long time since I did that split so I forgot a lot lol. Any one that cares to try and proceed further and has the time. Here is a [link ](https://github.com/jsloan117/AWSPics/tree/public_access) to what I got so far.

**Comment by tylerapplebaum** [comment]
I'll pull my app.yml and other modifications together tonight and create a PR in your repo.

**Comment by jsloan117** [comment]
Thanks for your patience in this. Lifes crazy sometimes :-). I've been able to get it to deploy successfully, but am getting a "Are you logged in? -- Error". I believe its related to the auto-generated index/error pages from the site-build, but am not 100% sure. Will continue to track this down as time permits.

**Comment by jsloan117** [comment]
As the PR shows, I've been able to figure this out. 

Not sure how everyone feels about the [custom 404 page](https://pics.jonathansloan.me/error.html) I've chosen it adds ~20 files to mix for it alone. 

I thought about using this simple [error page](https://codepen.io/robinselmer/pen/vJjbOZ) instead, thoughts?

@brettswift -- I didn't forget about your comment here either. I don't think it'd be easily done even more so with the passworded site, since you're dealing with signed cookies from the CloudFront. If it's possible I personally don't have a clue how to go about that and wasn't my personal objective/goal with this PR. I've sure they're up for a PR if you're inclined.

**Comment by tylerapplebaum** [comment]
I went ahead and merged files from this project and @jsloan117's project into a repo: https://github.com/tylerapplebaum/AWSPics

**Comment by jsloan117** [comment]
@tylerapplebaum looks like you did/pulled from my original code. While performing the updated version of this, my "public_access" branch, I noticed they the original creators of the 404 page I chose was broken, which is why I went after another space-related 404 page. I only chose space because what my site is for astrophotography.

I think if you have a  look at the code of that new branch of mine, should help to clean up that problem with the erorr.html page, I would even recommend the other link smaller one or one you want from codepen.io  they have lots of cool pages there.

**Comment by tylerapplebaum** [comment]
Gotcha. Didn't even notice you had a new branch out there! 

You did a great job respecting the different files and tagging yours with _public. I... did not. I'm happy to keep mine as a hard fork, while yours can likely be merged without incident.

**Comment by jpsim** [comment]
I have to say I love the contributions the three of you have been making. Really rewarding to see others interested in a one-off project I did years ago.

I'm a bit more inclined to showcase various forks in this project's README than to integrate all the various use cases in this project. That way, the "heft" of one use case (e.g. the complex password protection machinery) doesn't have to weigh on other use cases (e.g. passwordless version, UI tweaks like new 404 pages).

I'd be happy to merge PRs that add links to your respective forks highlighting their feature differences, with attribution.

**Comment by jsloan117** [comment]
Closing will update my stuff and provide a PR to update the readme to showcase.
