### ISSUE TITLE
S3 Rate Limit Delay Block

### ISSUE THREAD

**Issue by darrencurtis** [jpsim/AWSPics#38]
In Troubleshooting section of the Readme, it mentions "If SiteBuilder is hanging or having trouble completing, you may need to adjust the rate limiting delay block in index.js."

I presume the SiteBuilder lambda function would need the delay block but I'm unable to find the block in index.js. I'm not a programmer, so it may be there and I just don't know it, but my albums contain hundreds of pictures and I've experienced the site builder hang and partial file listings.

Would someone provide an example delay block of code, that I could insert and where exactly?  

Thanks for the great solution.
Darren

**Comment by jpsim** [comment]
It'd be to adjust this line: https://github.com/jpsim/AWSPics/blob/9baf59cf898a4468e193109bc98f1e47099e14af/site-builder/lib/delayUtils.js#L9

**Comment by darrencurtis** [comment]
Thanks JP.  Would I increase the value of "j" to increase the delay of writing to S3, like:
`for (let j = 7*10e6; j >= 0; j--) {`

**Comment by jpsim** [comment]
Yes that's right. You might need to experiment with the value to see what works well for you.
