### ISSUE TITLE
cloudfront to api gateway - internal server error

### ISSUE THREAD

**Issue by digitalkaoz** [jpsim/AWSPics#5]
hey @jpsim  great work!

i`ve ported this app/stack to terraform. all is working well (fixed a few bugs too) except one thing...the cdn doesnt correctly forwards requests to the login gateway+login_lambda.

do you have an idea what might be wrong? maybe we can (in private) inspect the CDN origins/cache-behavior together?

**Comment by jpsim** [comment]
Did you resolve this? Is your terraform port open source? I’d love to link to it from here if so. Also just interested in comparing with this.

Thanks!

**Comment by digitalkaoz** [comment]
Yes i resolved all issues. Will package it today ans drop you a Line...

JP Simard <notifications@github.com> schrieb am Di., 12. Dez. 2017, 03:09:
